ktor:
    application:
        modules:
            - com.emily.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  issuer: "http://127.0.0.1:8080"
  domain: "http://127.0.0.1:8080"
  audience: "emusic-users"
  realm: "ktor music-app"
